spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0719'
    url: jdbc:mysql://localhost:3302/SKALA
  thymeleaf:
    cache: false

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

developer:
  owner:
    name: dev-user
    role: developer
    level: student
  team:
    position: skala2
    detail: "class3"